function plot_MESH(Num, Vertices1, Faces1, CData1, X1, Y1, X2, Y2)
%CREATEFIGURE(Vertices1, Faces1, CData1, X1, Y1)
%  NUM: figure number
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  CDATA1:  patch cdata
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-May-2019 15:01:43

% Create figure
figure1 = figure(Num);
clf

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create patch
patch('Parent',axes1,'Vertices',Vertices1,'Faces',Faces1,...
    'FaceColor','interp',...
    'CData',CData1);

% Create open boundary plot
plot(X1,Y1,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create river boundary plot
plot(X2,Y2,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create ylabel
ylabel('Latitude (degtee)');

% Create xlabel
xlabel('Longtitude (degree)');

% Create title
title('Boundary nodes, mesh and water depth (m)');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[139.1 140.4]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[34.65 35.75]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1.2 1 1],'PlotBoxAspectRatio',...
    [1 1 1]);
set(gcf,'position',[Num*10,Num*10,800,600])
% Create colorbar
colorbar('peer',axes1);

